name = "SimpleWeave"
uuid = "f4131ab4-dd35-4b58-abd1-8879dd993ef2"
authors = ["Julius Krumbiegel <julius.krumbiegel@gmail.com>"]
version = "0.1.0"

[deps]
Markdown = "d6f4376e-aef5-505a-96c1-9c027394607a"
Weave = "44d3d7a6-8a23-5bf8-98c5-b353f8df5ec9"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
